try {

} catch(Exception | Exception2 | Exception3 | Exception4 varName) {
	
}